name: Publish image nightly
 
on:
  push: {}
 
jobs:
  # The steamcmd image fully uses the GitHub actions docker cache to avoid rebuilding it every night.
  build-steamcmd:
    name: Build steamcmd parent image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: steamcmd
          tags: ghcr.io/${{ github.actor }}/steamcmd:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Do not push image to the cache so we can retrieve the update.
  build-palworld-server:
    name: Build with Docker
    runs-on: ubuntu-20.04
    needs: build-steamcmd
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push palword image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: palworld
          tags: ghcr.io/${{ github.actor }}/palworld:latest
          build-args: STEAMCMD_IMAGE_TAG=ghcr.io/${{ github.actor }}/steamcmd
          cache-from: type=gha
