name: Publish image nightly
 
on:
  push: {}
 
jobs:
  build-with-docker:
    name: Build with Docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: cyr62110/palworld-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          